uploads = []
generated = []

[[outputs]]
id = "sDQ7PywzhtiH1sxZ_5f72"
uri = "file://artifacts/menotme/public/assets/audio/fan_yougotthis_m.mp3"
type = "audio"
title = "fan yougotthis m"

[[outputs]]
id = "O6mTBe_zsB4Xc28sLnjUa"
uri = "file://artifacts/menotme/public/assets/audio/fan_letsgo_m.mp3"
type = "audio"
title = "fan letsgo m"

[[outputs]]
id = "pfhTN-tj-ULuHJ4ORdkd4"
uri = "file://artifacts/menotme/public/assets/audio/fan_onemore_m.mp3"
type = "audio"
title = "fan onemore m"

[[outputs]]
id = "hegZ4U0pIe4_-AZfPS14V"
uri = "file://artifacts/menotme/public/assets/audio/fan_onemore_f.mp3"
type = "audio"
title = "fan onemore f"

[[outputs]]
id = "rlqxybfJZiPqDs6NeGMZs"
uri = "file://artifacts/menotme/public/assets/audio/fan_keepgoing_f.mp3"
type = "audio"
title = "fan keepgoing f"

[[outputs]]
id = "eDX0GvkIOIeyGUWubEI-W"
uri = "file://artifacts/menotme/public/assets/audio/doubt_youllmiss_m.mp3"
type = "audio"
title = "doubt youllmiss m"

[[outputs]]
id = "DkKZ4ybwPVDrS8DWiUsRj"
uri = "file://artifacts/menotme/public/assets/audio/doubt_nottoday_f.mp3"
type = "audio"
title = "doubt nottoday f"

[[outputs]]
id = "MOJwiF4SNs03uqmkbBgPz"
uri = "file://artifacts/menotme/public/assets/audio/fan_whatashot_f.mp3"
type = "audio"
title = "fan whatashot f"

[[outputs]]
id = "xdCvOV3Ys15GKxTs6sSw-"
uri = "file://artifacts/menotme/public/assets/audio/doubt_cantkeepup_f.mp3"
type = "audio"
title = "doubt cantkeepup f"

[[outputs]]
id = "T27t5TS1VzZy_nUjbznYZ"
uri = "file://artifacts/menotme/public/assets/audio/doubt_letssee_m.mp3"
type = "audio"
title = "doubt letssee m"

[[outputs]]
id = "ItasTqQ0fMCWiosth1nQS"
uri = "file://artifacts/menotme/public/assets/audio/doubt_proveit_f.mp3"
type = "audio"
title = "doubt proveit f"

[[outputs]]
id = "jIpFE-SjL-fdfx_kWtLnJ"
uri = "file://artifacts/menotme/public/assets/audio/cheer_small.mp3"
type = "audio"
title = "small cheer"

[[outputs]]
id = "9JYEx3lOcKM2i5Qw2wxXl"
uri = "file://artifacts/menotme/public/assets/audio/doubt_letssee_f.mp3"
type = "audio"
title = "doubt letssee f"

[[outputs]]
id = "RAke1S1nEf8olWEq95ztW"
uri = "file://artifacts/menotme/public/assets/audio/chant_onemore.mp3"
type = "audio"
title = "one more chant"

[[outputs]]
id = "mWe8kZT_2kLoyY-jqip6V"
uri = "file://artifacts/menotme/public/assets/audio/ambience_loop.mp3"
type = "audio"
title = "arena ambience loop"

[[outputs]]
id = "KHFuijy9BAP3hKUOpbhph"
uri = "file://artifacts/menotme/public/assets/audio/beat_loop.mp3"
type = "audio"
title = "arena beat loop"

[[outputs]]
id = "vYStb5YpbH5-YK925QmPi"
uri = "file://artifacts/menotme/public/assets/audio/intro_rhythm.mp3"
type = "audio"
title = "arena intro rhythm"

[[outputs]]
id = "AiGdlt3yQuT9-Tr4NBi3R"
uri = "file://artifacts/menotme/public/assets/audio/comm_win_1.mp3"
type = "audio"
title = "comm_win_1"

[[outputs]]
id = "em_tsqZht_vGDP2qWPUfK"
uri = "file://artifacts/menotme/public/assets/audio/comm_new_1.mp3"
type = "audio"
title = "comm_new_1"

[[outputs]]
id = "QpyVaU7T0GHBQWDPC4_xE"
uri = "file://artifacts/menotme/public/assets/audio/comm_loss_2.mp3"
type = "audio"
title = "comm_loss_2"

[[outputs]]
id = "q3MxwnTpix_KfKjP3vVXY"
uri = "file://artifacts/menotme/public/assets/audio/comm_streakbig_1.mp3"
type = "audio"
title = "comm_streakbig_1"

[[outputs]]
id = "f_rfa0ohuBNxGFMF8eN0_"
uri = "file://artifacts/menotme/public/assets/audio/comm_streak_1.mp3"
type = "audio"
title = "comm_streak_1"

[[outputs]]
id = "c8ERbbF_QMEX7GSPPB4X2"
uri = "file://artifacts/menotme/public/assets/audio/comm_out_1.mp3"
type = "audio"
title = "comm_out_1"

[[outputs]]
id = "9u7yAcErPRHDe1CSDsn5j"
uri = "file://artifacts/menotme/public/assets/audio/insp_q04.mp3"
type = "audio"
title = "insp q04"

[[outputs]]
id = "BVDj1-0-6nBh_Cv1Y54fU"
uri = "file://artifacts/menotme/public/assets/audio/insp_q06.mp3"
type = "audio"
title = "insp q06"

[[outputs]]
id = "T8HKEgPLTm-sLOnVm5El-"
uri = "file://artifacts/menotme/public/assets/audio/insp_q07.mp3"
type = "audio"
title = "insp q07"

[[outputs]]
id = "UIFyPYuS0d-djTCyobB3-"
uri = "file://artifacts/menotme/public/assets/audio/insp_q08.mp3"
type = "audio"
title = "insp q08"

[[outputs]]
id = "dz_IwzgFmFc8QpYVN_rLq"
uri = "file://artifacts/menotme/public/assets/audio/insp_q05.mp3"
type = "audio"
title = "insp q05"

[[outputs]]
id = "ENtwLQZRdHg40_ID05Qjp"
uri = "file://artifacts/menotme/public/assets/audio/insp_q10.mp3"
type = "audio"
title = "insp q10"

[[outputs]]
id = "DXCxiTZWn2uQ4zaNeVq6X"
uri = "file://artifacts/menotme/public/assets/audio/insp_q13.mp3"
type = "audio"
title = "insp q13"

[[outputs]]
id = "G-GU3LxGlxeqJz9KGwodn"
uri = "file://artifacts/menotme/public/assets/audio/insp_q14.mp3"
type = "audio"
title = "insp q14"

[[outputs]]
id = "tiwcmalV-TKkMRXKQDUAW"
uri = "file://artifacts/menotme/public/assets/audio/insp_q12.mp3"
type = "audio"
title = "insp q12"

[[outputs]]
id = "jZk2eE5YV4w_Puk4sYRXQ"
uri = "file://artifacts/menotme/public/assets/audio/insp_q09.mp3"
type = "audio"
title = "insp q09"

[[outputs]]
id = "kmpnkwaSCfSMIeOB7ZaV_"
uri = "file://artifacts/menotme/public/assets/audio/insp_q16.mp3"
type = "audio"
title = "insp q16"

[[outputs]]
id = "TYTxEYQX2b25bP5mlbXsn"
uri = "file://artifacts/menotme/public/assets/audio/insp_q11.mp3"
type = "audio"
title = "insp q11"

[[outputs]]
id = "cjGPcz7SZYTahy-Vq_Wqh"
uri = "file://artifacts/menotme/public/assets/audio/insp_q20.mp3"
type = "audio"
title = "insp q20"

[[outputs]]
id = "E0GxgtC6kwH-X4yHG5xiw"
uri = "file://artifacts/menotme/public/assets/audio/insp_q19.mp3"
type = "audio"
title = "insp q19"

[[outputs]]
id = "rBAielJ8fy4m6ghUgXXu4"
uri = "file://artifacts/menotme/public/assets/audio/insp_q24.mp3"
type = "audio"
title = "insp q24"

[[outputs]]
id = "tyPpllcDRFh4gSDebgIAF"
uri = "file://artifacts/menotme/public/assets/audio/insp_q21.mp3"
type = "audio"
title = "insp q21"

[[outputs]]
id = "YdvBJ4ZoXAQNVxfvwq07h"
uri = "file://artifacts/menotme/public/assets/audio/insp_q23.mp3"
type = "audio"
title = "insp q23"

[[outputs]]
id = "ALRsKV_cozGnEBQCqIUjv"
uri = "file://artifacts/menotme/public/assets/audio/insp_q26.mp3"
type = "audio"
title = "insp q26"

[[outputs]]
id = "k25TnpoAW-363pHqXCFxT"
uri = "file://artifacts/menotme/public/assets/audio/insp_q27.mp3"
type = "audio"
title = "insp q27"

[[outputs]]
id = "gWEHASoPBzmeDtFAE5s1j"
uri = "file://artifacts/menotme/public/assets/audio/insp_q28.mp3"
type = "audio"
title = "insp q28"

[[outputs]]
id = "xQFsFvGe8fpEkWsiCctg-"
uri = "file://artifacts/menotme/public/assets/audio/insp_q31.mp3"
type = "audio"
title = "insp q31"

[[outputs]]
id = "xvD1k0fwo7F2QWbUS1VhW"
uri = "file://artifacts/menotme/public/assets/audio/insp_q33.mp3"
type = "audio"
title = "insp q33"

[[outputs]]
id = "laZufbyHvGj3rbzZKRUO0"
uri = "file://artifacts/menotme/public/assets/audio/insp_q35.mp3"
type = "audio"
title = "insp q35"

[[outputs]]
id = "RPwWnzbTDCj6ycIQlkeSV"
uri = "file://artifacts/menotme/public/assets/audio/insp_q36.mp3"
type = "audio"
title = "insp q36"

[[outputs]]
id = "h3wD1FK1AUAVFrdPeKsyx"
uri = "file://artifacts/menotme/public/assets/audio/insp_q40.mp3"
type = "audio"
title = "insp q40"

[[outputs]]
id = "irG9E0MNsUc3EaxEoTL4a"
uri = "file://artifacts/menotme/public/assets/audio/insp_q38.mp3"
type = "audio"
title = "insp q38"

[[outputs]]
id = "FsgThnT87O6hO8WXGvKCc"
uri = "file://artifacts/menotme/public/assets/audio/insp_q37.mp3"
type = "audio"
title = "insp q37"

[[outputs]]
id = "QPNtrF7f877jREO6L5Ojf"
uri = "file://artifacts/menotme/public/assets/audio/insp_q42.mp3"
type = "audio"
title = "insp q42"

[[outputs]]
id = "upcMbQzDI-Wa7CrRZ-4Kd"
uri = "file://artifacts/menotme/public/assets/audio/insp_q41.mp3"
type = "audio"
title = "insp q41"

[[outputs]]
id = "QWat9XmNXtvhhG7C4cphB"
uri = "file://artifacts/menotme/public/assets/audio/insp_q43.mp3"
type = "audio"
title = "insp q43"

[[outputs]]
id = "l5UzUhuVV6GZtodzUupvB"
uri = "file://artifacts/menotme/public/assets/audio/insp_q45.mp3"
type = "audio"
title = "insp q45"

[[outputs]]
id = "sHm6Sk21Elqc-RXCZuWrP"
uri = "file://artifacts/menotme/public/assets/audio/insp_q46.mp3"
type = "audio"
title = "insp q46"

[[outputs]]
id = "1wdss1seZwb4uu07RSyyD"
uri = "file://artifacts/menotme/public/assets/audio/insp_q48.mp3"
type = "audio"
title = "insp q48"

[[outputs]]
id = "0kV3ayxxt56C6euiBgcrT"
uri = "file://artifacts/menotme/public/assets/audio/insp_q47.mp3"
type = "audio"
title = "insp q47"

[[outputs]]
id = "q12oTmdF8ImovP7gAnP5U"
uri = "file://artifacts/menotme/public/assets/audio/insp_q49.mp3"
type = "audio"
title = "insp q49"

[[outputs]]
id = "a5Ul3Zt_Ma_MopXPHXfP-"
uri = "file://artifacts/menotme/public/assets/audio/insp_q50.mp3"
type = "audio"
title = "insp q50"

[[outputs]]
id = "aaZklEMSBXYCA4xrux_kb"
uri = "file://artifacts/menotme/public/assets/audio/insp_q52.mp3"
type = "audio"
title = "insp q52"

[[outputs]]
id = "4pDNYgBA8TCa-jL8W1I7s"
uri = "file://artifacts/menotme/public/assets/audio/insp_q54.mp3"
type = "audio"
title = "insp q54"

[[outputs]]
id = "2XTMOcPgmA48D6rp8KzX7"
uri = "file://artifacts/menotme/public/assets/audio/insp_q55.mp3"
type = "audio"
title = "insp q55"

[[outputs]]
id = "LmLHAWL_jb2Bwr5dO1oMK"
uri = "file://artifacts/menotme/public/assets/audio/insp_q56.mp3"
type = "audio"
title = "insp q56"

[[outputs]]
id = "Ahvme17aBxoFd0S7ZD_yI"
uri = "file://artifacts/menotme/public/assets/audio/insp_q60.mp3"
type = "audio"
title = "insp q60"

[[outputs]]
id = "q6ePmMQj3EoXdszVEtWPd"
uri = "file://artifacts/menotme/public/assets/audio/insp_q57.mp3"
type = "audio"
title = "insp q57"

[[outputs]]
id = "qBXlqNXiufqoqfO2-1feK"
uri = "file://artifacts/menotme/public/assets/audio/insp_q61.mp3"
type = "audio"
title = "insp q61"

[[outputs]]
id = "4aY1W_95pN_CCqLzMwUMS"
uri = "file://artifacts/menotme/public/assets/audio/insp_q64.mp3"
type = "audio"
title = "insp q64"

[[outputs]]
id = "R8hcf_Wpc9Irlg3ILD1Em"
uri = "file://artifacts/menotme/public/assets/audio/insp_q58.mp3"
type = "audio"
title = "insp q58"

[[outputs]]
id = "41eI1QeLNqUnGyaVdceF6"
uri = "file://artifacts/menotme/public/assets/audio/insp_q62.mp3"
type = "audio"
title = "insp q62"
